using Application.Features.Foods.Commands;
using Application.Features.Foods.Dtos;
using Domain.Entities.Foods;

namespace Application.Features.Foods.Profiles;

public class FoodProfile : Profile
{
    public FoodProfile()
    {
        CreateMap<Food, FoodDto>()
            .ForMember(dest => dest.IsFavorite, opt => opt.MapFrom(src =>
                src.Favorites.Any()))
            .ForMember(dest => dest.Star, opt => opt.MapFrom(src =>
                src.Ratings.Any()
                    ? (byte)Math.Round(src.Ratings.Average(r => r.Star))
                    : (byte)0))
            .ForMember(dest => dest.RateCount, opt => opt.MapFrom(src =>
                src.Ratings.Count))
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
            .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
            .ForMember(dest => dest.Ingredients, opt => opt.MapFrom(src => src.Ingredients))
            .ForMember(dest => dest.ImageUrl, opt => opt.MapFrom(src => src.ImageUrl))
            .ForMember(dest => dest.Price, opt => opt.MapFrom(src => src.Price))
            .ForMember(dest => dest.DiscountPercent, opt => opt.MapFrom(src => src.DiscountPercent))
            .ForMember(dest => dest.IsSpecialOffer, opt => opt.MapFrom(src => src.IsSpecialOffer));

        CreateMap<FoodDto, Food>()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
            .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
            .ForMember(dest => dest.Ingredients, opt => opt.MapFrom(src => src.Ingredients))
            .ForMember(dest => dest.ImageUrl, opt => opt.MapFrom(src => src.ImageUrl))
            .ForMember(dest => dest.Price, opt => opt.MapFrom(src => src.Price))
            .ForMember(dest => dest.DiscountPercent, opt => opt.MapFrom(src => src.DiscountPercent))
            .ForMember(dest => dest.IsSpecialOffer, opt => opt.MapFrom(src => src.IsSpecialOffer));

        CreateMap<CreateFoodCommand, Food>()
            .ForMember(dest => dest.Id, opt => opt.Ignore()) // will be generated by EF Core
            .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
            .ForMember(dest => dest.Ingredients, opt => opt.MapFrom(src => src.Ingredients))
            .ForMember(dest => dest.ImageUrl, opt => opt.MapFrom(src => src.ImageUrl))
            .ForMember(dest => dest.Price, opt => opt.MapFrom(src => src.Price))
            .ForMember(dest => dest.DiscountPercent, opt => opt.MapFrom(src => src.DiscountPercent))
            .ForMember(dest => dest.IsSpecialOffer, opt => opt.MapFrom(src => src.IsSpecialOffer));

    }
}